api_platform:
    title: "BileMo API"
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
         versions: [3]
         api_keys:
             apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            items_per_page: 3